import React, {useEffect, useState} from 'react';
import {NavigationContainer} from '@react-navigation/native';
import {createNativeStackNavigator} from '@react-navigation/native-stack';
import AsyncStorage from '@react-native-async-storage/async-storage';
import {View, Text, TextInput, TouchableOpacity, FlatList, Image, StyleSheet, Alert, ScrollView} from 'react-native';
import * as ImagePicker from 'expo-image-picker';

const Stack=createNativeStackNavigator();
const demo=[
 {id:'1',title:'2 BHK Family House',location:'Sangareddy',rent:'₹8,000',bhk:'2 BHK',image:'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=900&q=80'},
 {id:'2',title:'1 BHK House',location:'Metpally',rent:'₹5,500',bhk:'1 BHK',image:'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80'}
];

function Button({title,onPress,outline=false}){return <TouchableOpacity onPress={onPress} style={[s.btn,outline&&s.outline]}><Text style={[s.btnText,outline&&s.outlineText]}>{title}</Text></TouchableOpacity>}
function Home({navigation}){return <View style={s.center}><Text style={s.logo}>NIVAS</Text><Text style={s.tag}>Find a house. Find a home.</Text><Button title="FREE • CUSTOMER / TENANT" onPress={()=>navigation.navigate('Auth',{role:'tenant'})}/><Button title="HOUSE OWNER" onPress={()=>navigation.navigate('Auth',{role:'owner'})} outline/><Text style={s.note}>Tenants register free • Owners list properties for ₹99</Text></View>}

function Auth({navigation,route}){const role=route.params.role; const [mode,setMode]=useState('register'); const [name,setName]=useState(''); const [phone,setPhone]=useState(''); const [pass,setPass]=useState('');
const submit=async()=>{if(!phone||!pass||(mode==='register'&&!name))return Alert.alert('Required','Please fill all fields'); if(role==='owner'&&mode==='register'){await AsyncStorage.setItem('pendingOwner',JSON.stringify({name,phone,pass})); return navigation.navigate('OwnerPayment');} await AsyncStorage.setItem('user',JSON.stringify({name,phone,role})); navigation.replace(role==='tenant'?'CustomerHome':'OwnerHome');};
return <ScrollView contentContainerStyle={s.form}><Text style={s.h1}>{role==='tenant'?'Customer / Tenant':'House Owner'}</Text><Text style={s.muted}>{mode==='register'?'Create your account':'Login to your account'}</Text>{mode==='register'&&<TextInput style={s.input} placeholder="Full name" value={name} onChangeText={setName}/>}<TextInput style={s.input} placeholder="Mobile number" keyboardType="phone-pad" value={phone} onChangeText={setPhone}/><TextInput style={s.input} placeholder="Password" secureTextEntry value={pass} onChangeText={setPass}/><Button title={mode==='register'?(role==='owner'?'CONTINUE TO ₹99':'CREATE FREE ACCOUNT'):'LOGIN'} onPress={submit}/><TouchableOpacity onPress={()=>setMode(mode==='register'?'login':'register')}><Text style={s.link}>{mode==='register'?'Already have an account? Login':'New user? Register'}</Text></TouchableOpacity></ScrollView>}

function OwnerPayment({navigation}){return <View style={s.center}><Text style={s.h1}>Owner Registration</Text><Text style={s.pay}>₹99</Text><Text style={s.muted}>Property listing registration fee</Text><Button title="PAY ₹99 & CONTINUE" onPress={async()=>{const p=await AsyncStorage.getItem('pendingOwner'); await AsyncStorage.setItem('user',JSON.stringify({...JSON.parse(p),role:'owner',paid:true})); navigation.replace('OwnerHome')}}/><Text style={s.note}>Payment screen is a setup placeholder. Connect your verified payment gateway before publishing.</Text></View>}

function CustomerHome({navigation}){const [q,setQ]=useState(''); const [max,setMax]=useState(''); const data=demo.filter(x=>x.location.toLowerCase().includes(q.toLowerCase())&&(!max||Number(x.rent.replace(/\\D/g,''))<=Number(max))); return <View style={s.page}><Text style={s.h1}>Search Houses</Text><TextInput style={s.input} placeholder="Location" value={q} onChangeText={setQ}/><TextInput style={s.input} placeholder="Maximum rent" keyboardType="numeric" value={max} onChangeText={setMax}/><FlatList data={data} keyExtractor={x=>x.id} renderItem={({item})=><TouchableOpacity style={s.card} onPress={()=>navigation.navigate('Property',{item})}><Image source={{uri:item.image}} style={s.photo}/><View style={s.cardbody}><Text style={s.title}>{item.title}</Text><Text>{item.location} • {item.bhk}</Text><Text style={s.rent}>{item.rent}/month</Text></View></TouchableOpacity>}/></View>}

function Property({route}){const x=route.params.item; return <ScrollView style={s.page}><Image source={{uri:x.image}} style={s.hero}/><Text style={s.h1}>{x.title}</Text><Text style={s.muted}>{x.location} • {x.bhk}</Text><Text style={s.rent}>{x.rent}/month</Text><Text style={s.desc}>Contact details are shown by the owner after completing the applicable registration/payment flow.</Text></ScrollView>}

function OwnerHome({navigation}){const [title,setTitle]=useState(''); const [location,setLocation]=useState(''); const [rent,setRent]=useState(''); const [bhk,setBhk]=useState('2 BHK'); const [image,setImage]=useState(null);
const pick=async()=>{const r=await ImagePicker.requestMediaLibraryPermissionsAsync(); if(!r.granted)return Alert.alert('Permission required'); const p=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],quality:.7}); if(!p.canceled)setImage(p.assets[0].uri)};
const add=async()=>{if(!title||!location||!rent)return Alert.alert('Required','Enter property details'); const old=JSON.parse((await AsyncStorage.getItem('properties'))||'[]'); old.push({id:Date.now().toString(),title,location,rent:`₹${rent}`,bhk,image:image||demo[0].image}); await AsyncStorage.setItem('properties',JSON.stringify(old)); Alert.alert('Success','Property added'); setTitle('');setLocation('');setRent('');setImage(null)};
return <ScrollView contentContainerStyle={s.form}><Text style={s.h1}>Add Property</Text><TextInput style={s.input} placeholder="Property title" value={title} onChangeText={setTitle}/><TextInput style={s.input} placeholder="Location" value={location} onChangeText={setLocation}/><TextInput style={s.input} placeholder="Monthly rent" keyboardType="numeric" value={rent} onChangeText={setRent}/><TextInput style={s.input} placeholder="BHK" value={bhk} onChangeText={setBhk}/>{image&&<Image source={{uri:image}} style={s.preview}/>}<Button title="CHOOSE PROPERTY PHOTO" onPress={pick} outline/><Button title="PUBLISH PROPERTY" onPress={add}/><Text style={s.note}>Only paid owner accounts should use this screen.</Text></ScrollView>}

function App(){return <NavigationContainer><Stack.Navigator><Stack.Screen name="Home" component={Home} options={{headerShown:false}}/><Stack.Screen name="Auth" component={Auth} options={{title:'Account'}}/><Stack.Screen name="OwnerPayment" component={OwnerPayment} options={{title:'Owner Registration'}}/><Stack.Screen name="CustomerHome" component={CustomerHome} options={{title:'NIVAS'}}/><Stack.Screen name="Property" component={Property} options={{title:'Property'}}/><Stack.Screen name="OwnerHome" component={OwnerHome} options={{title:'Owner'}}/></Stack.Navigator></NavigationContainer>}
const s=StyleSheet.create({center:{flex:1,justifyContent:'center',padding:24,backgroundColor:'#fff'},page:{flex:1,padding:16,backgroundColor:'#fff'},form:{padding:24,backgroundColor:'#fff',flexGrow:1},logo:{fontSize:52,fontWeight:'900',textAlign:'center',letterSpacing:5},tag:{textAlign:'center',color:'#666',marginBottom:40},btn:{backgroundColor:'#111',padding:16,borderRadius:10,marginVertical:8,alignItems:'center'},btnText:{color:'#fff',fontWeight:'800'},outline:{backgroundColor:'#fff',borderWidth:1,borderColor:'#111'},outlineText:{color:'#111'},note:{textAlign:'center',color:'#777',fontSize:12,marginTop:18},h1:{fontSize:26,fontWeight:'800',marginBottom:6},muted:{color:'#777',marginBottom:18},input:{borderWidth:1,borderColor:'#ddd',borderRadius:10,padding:14,marginVertical:7,fontSize:16},link:{textAlign:'center',marginTop:16,fontWeight:'700'},pay:{fontSize:54,fontWeight:'900',marginVertical:10},card:{borderWidth:1,borderColor:'#eee',borderRadius:12,overflow:'hidden',marginBottom:14},photo:{width:'100%',height:180},cardbody:{padding:12},title:{fontSize:18,fontWeight:'800'},rent:{fontSize:20,fontWeight:'800',marginTop:8},hero:{width:'100%',height:280},desc:{marginTop:20,lineHeight:22},preview:{width:'100%',height:200,borderRadius:10,marginVertical:10}});
export default App;
